baseURL = "https://n0rdy.foo/"
languageCode = "en-us"
title = "n0rdy personal blog"
theme = "poison"

enableRobotsTXT = true
pluralizelisttitles = false
paginate = 5

[params]
    brand = "n0rdy"
    brand_image = "/images/avatar.jpg"
    description = "Exploring software engineering and tech"
    dark_mode = true
    favicon = "/favicon.ico"

    menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = false},
        {Name = "Series", URL = "/series/", Pre = "Recent", HasChildren = false},
        {Name = "Tags", URL = "/tags/", HasChildren = false},
    ]

    # Remark42
    remark42 = true
    remark42_host = "https://www.remark42.n0rdy.foo"
    remark42_site_id = "remark42.n0rdy.foo"

    # Plausible
    plausible = true
    plausible_domain = "n0rdy.foo"
    plausible_script = "https://plausible.n0rdy.foo/js/script.js"

    # Listmonk
    listmonk = true
    listmonk_host = "https://mail.n0rdy.foo"
    listmonk_subscription_list_uiid = "3ba79b71-880f-417d-9587-d388b62e0986"
    listmonk_subscription_form_text = "Receive an email once a new post is published"
    listmonk_subscription_success_message = "Almost there! =) Please, check your email to confirm subscription. Check your spam folder if you didn't get the email."
    listmonk_subcription_error_message = "Something went wrong =( Please, try again later."

    github_url = "https://github.com/n0rdy"
    bluesky_url = "https://bsky.app/profile/n0rdy.foo"
    twitter_url = "https://twitter.com/_n0rdy_"
    mastodon_url = "https://mastodon.social/@n0rdy"
    email_url = "mailto://hello@n0rdy.foo"

    rss_icon = true
    rss_section = "posts"

    # Hex colors for sidebar
    sidebar_bg_color = "#202020"            # default is #202020
    sidebar_img_border_color = "#515151"    # default is #515151
    sidebar_p_color = "#909090"             # default is #909090
    sidebar_h1_color = "#FFF"               # default is #FFF
    sidebar_a_color = "#FFF"                # default is #FFF
    sidebar_socials_color = "#FFF"          # default is #FFF
    moon_sun_color = "#FFF"                 # default is #FFF
    moon_sun_background_color = "#515151"   # default is #515151

    # Hex colors for content in light mode
    text_color = "#222"             # default is #222
    content_bg_color = "#FAF9F6"    # default is #FAF9F6
    post_title_color = "#303030"    # default is #303030
    list_color = "#5a5a5a"          # default is #5a5a5a
    link_color = "#268bd2"          # default is #268bd2
    date_color = "#515151"          # default is #515151

    # Hex colors for content in dark mode
    text_color_dark = "#eee"            # default is #eee
    content_bg_color_dark = "#121212"   # default is #121212
    post_title_color_dark = "#DBE2E9"   # default is #DBE2E9
    list_color_dark = "#9d9d9d"         # default is #9d9d9d
    link_color_dark = "#268bd2"         # default is #268bd2
    date_color_dark = "#9a9a9a"         # default is #9a9a9a

[markup.goldmark.renderer]
    unsafe = true

[params.meta]
    favicon = true

[taxonomies]
    series = 'series'
    tags = 'tags'